### ISSUE TITLE
Install Question -  MS Office Dependencies

### ISSUE THREAD

**Issue by johnbabb** [CaioProiete/NetOffice-NuGet#2]
I was looking for detailed information about install and configuration of the libs and a list of dependencies the libs have.  Aside from the version of the .NET framework, are there any MS Office com objects or dlls that we need to include in our bin to run NetOffice?

**Comment by CaioProiete** [comment]
Hi @johnbabb, as far as I understand, the files included in the NuGet packages are the only ones you need to include in your bin. NetOffice uses latebinding calls via interop, so you don't need the Office assemblies that is normally added as a reference (Office PIA) nor VSTO assemblies.

My experience with NetOffice only involved Excel so far - I have several Excel add-ins deployed in production that only use the Excel NuGet packages and don't require any other dependencies (apart from having Excel installed on the machine where the add-in runs, of course).

If you want to double-check, ask this question on the NetOffice discussion board (http://netoffice.codeplex.com/discussions) and Sebastian (the core developer of NetOffice) might be able to answer.
