### ISSUE TITLE
100000 lines slow transfer ?

### ISSUE THREAD

**Issue by mummyildiz** [caioproiete/NetOffice-NuGet#4]
100,000 lines of recording are transferring very slowly and are waiting so long. Is there a solution to this?
(7 columns)

**Comment by caioproiete** [comment]
@mummyildiz For now issues are still tracked via CodePlex ( http://netoffice.codeplex.com/workitem/list/basic ). Please raise this one there, and add more details please.

**Comment by erikaleblanc88** [comment]
Moved to https://github.com/netoffice/NetOffice/issues/11
