### ISSUE TITLE
Update with new Version

### ISSUE THREAD

**Issue by matteshe** [caioproiete/NetOffice-NuGet#6]
Hi,

this projects seems a bit dead. The last and only first stable version is 1.7.3. Only a pre 1.7.4 from 2015 is as unstable version available. There is an offical new NetOffice Version 1.7.4 from 2018. How can I get an up-to-date version via nuget in Visual Studio? When do you provide some updates?

**Comment by caioproiete** [comment]
@matteshe I'm working on the next version of [NetOffice](https://github.com/netoffice) and will update the NuGet packages soon.

**Comment by abrenner85** [comment]
When you expect to have the new package?

**Comment by caioproiete** [comment]
@abrenner85 The NuGet packages are in sync with the source code and will be published to nuget.org together with upcoming releases.
